apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xo6ehrghe-python
  janus-idp.io/tekton: xo6ehrghe-python
  backstage.io/kubernetes-id: xo6ehrghe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xo6ehrghe-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
