apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xo6ehrghe-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xo6ehrghe-python 
  name: xo6ehrghe-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xo6ehrghe-python 
